"""The steady solve: it is the fixed point of the step, and its gradient is exact."""

import dataclasses
import functools
import os

import jax
import jax.numpy as jnp
import numpy as np
import pytest

from lmhdx.bc import NEUMANN, PERIODIC, BoundaryCondition
from lmhdx.core3d import ChannelProblem, duct_problem, step, zero_velocity
from lmhdx.grid import Grid, uniform_faces, wall_resolving_faces
from lmhdx.steady import solve_steady_state, steady_residual
from validation.shercliff import flow_rate, hartmann_wall_current, quadrant_flow_rate

pytestmark = pytest.mark.numerical

PERIODIC_X = BoundaryCondition(PERIODIC)
WALL = BoundaryCondition(NEUMANN)

# Mean velocity of a unit-forced insulating square duct, from validation.shercliff at the
# resolution of 64 points per direction; Ha 1000 from its parity quadrant on 48 mapped points,
# because the full-domain solve at 96 points is 0.60 % high there. Held as constants so a
# solver test costs a solve and not a dense spectral factorization;
# `test_the_reference_values_are_what_the_spectral_solve_returns` regenerates them.
REFERENCE_FLOW_RATE = {
    0.0: 0.140577010,
    5.0: 0.098192820,
    20.0: 0.038321780,
    100.0: 0.009054397,
    300.0: 0.003160369,
    1000.0: 0.000972103,
}


def _duct(
    cells: int,
    hartmann: float,
    *,
    ratio: float | None = None,
    dt: float = 1.0,
    conductance: float = 0.0,
    conductivity: float = 1.0,
) -> ChannelProblem:
    """A square duct; ``ratio`` clusters cells into the two wall layers.

    ``conductance`` is the wall conductance ratio of the two walls normal to the
    field, which is Hunt's configuration. Only ``sigma B^2`` is physical, so the
    field is scaled to keep the Hartmann number fixed when the conductivity moves.
    """
    if ratio is None:
        transverse = spanwise = uniform_faces(cells, -1.0, 1.0)
    else:
        transverse = wall_resolving_faces(
            cells, -1.0, 1.0, layer_thickness=1.0 / hartmann, cells_in_layer=6, max_ratio=ratio
        )
        spanwise = wall_resolving_faces(
            cells, -1.0, 1.0, layer_thickness=1.0 / np.sqrt(hartmann), cells_in_layer=6, max_ratio=ratio
        )
    return ChannelProblem(
        grid=Grid(uniform_faces(1, 0.0, 1.0), transverse, spanwise),
        conditions=(PERIODIC_X, WALL, WALL),
        conductivity=conductivity if hartmann else 0.0,
        magnetic_field=(0.0, hartmann / np.sqrt(conductivity), 0.0),
        forcing=(1.0, 0.0, 0.0),
        dt=dt,
        wall_conductance=(0.0, conductance, 0.0),
    )


# Hunt's duct, keyed by (Ha, wall conductance ratio): Ha 20 on 64 points, Ha 300 on the
# mapped quadrant (48 points, beta 5), regenerated by the Hunt test below.
HUNT_FLOW_RATE = {
    (20.0, 0.027): 0.027577890,
    (20.0, 0.100): 0.017148080,
    (300.0, 0.027): 0.00041667,
    (300.0, 0.100): 0.00017073,
}
# The current each Hartmann wall carries across its midplane in Hunt's Ha 20 duct, from
# validation.shercliff.hartmann_wall_current on 64 points (48 and 80 points agree to 3e-5;
# the midplane sheet current -c dphi/dz to 1e-5 and 6e-4); regenerated by the Hunt
# reference test below.
HUNT_WALL_CURRENT = {0.027: 0.016748551, 0.100: 0.032252758}


def _mean(problem: ChannelProblem, velocity) -> float:
    volumes = np.asarray(problem.grid.cell_volumes())[0]
    return float((np.asarray(velocity[0].data)[0] * volumes).sum() / volumes.sum())


def test_the_residual_vanishes_exactly_at_a_fixed_point_of_the_step():
    """The two have to agree on what steady means, or the solve answers a different question."""
    problem = _duct(8, 5.0, dt=0.02)
    factorization = problem.factorization()
    viscous = problem.viscous_factorizations()
    velocity = zero_velocity(problem)
    for _ in range(300):
        velocity, _, _ = step(velocity, problem, factorization, viscous)
    residual = steady_residual(velocity, problem, factorization)
    size = max(float(jnp.max(jnp.abs(velocity[0].data))), 1.0)
    assert max(float(jnp.max(jnp.abs(field.data))) for field in residual) < 1e-9 * size


def test_the_steady_solve_reproduces_the_marched_state_far_faster(monkeypatch):
    """The steady solve reaches the marched state with far fewer projections than marching.

    A claim about the method, not about the machine, so the work is counted rather
    than timed: both paths are built from the same projection, and a clock also
    measures host load and whether the solve's loops were already compiled.
    ``jax.debug.callback`` fires once per execution, inside compiled loops too, so
    the counts are applications and not traces.
    """
    import lmhdx.core3d
    import lmhdx.steady

    projections = [0]
    project = lmhdx.core3d.project

    def bump():
        projections[0] += 1

    def counted_project(*args, **kwargs):
        jax.debug.callback(bump)
        return project(*args, **kwargs)

    monkeypatch.setattr(lmhdx.core3d, "project", counted_project)
    monkeypatch.setattr(lmhdx.steady, "project", counted_project)

    problem = _duct(12, 5.0, dt=0.02)
    factorization = problem.factorization()
    viscous = problem.viscous_factorizations()
    velocity = zero_velocity(problem)
    for _ in range(300):
        velocity, _, _ = step(velocity, problem, factorization, viscous)
    jax.effects_barrier()
    marched = projections[0]
    assert marched == 300

    projections[0] = 0
    solution = solve_steady_state(problem, pseudo_step=100.0)
    jax.effects_barrier()
    assert abs(_mean(problem, solution.velocity) - _mean(problem, velocity)) < 1e-8
    # This insulating Stokes duct is one CG solve, whose operator and preconditioner both
    # project through the counted name, so the count is the work. Newton-Krylov projects
    # the linearised residual in the tangent, where no callback fires, but each such
    # application is paired with a counted one: a Krylov iteration with its
    # preconditioner, a restart cycle's true residual with its Newton step's residual.
    # Doubling the count therefore bounds the work of either route.
    newton = projections[0]
    # A count of zero means the solve no longer projects through the patched names, and
    # would pass the comparison below without measuring anything.
    assert newton > 0, "the steady solve applied no counted projection; the counter no longer sees it"
    assert 2 * newton < marched, (
        f"steady solve: {newton} projections (bound {2 * newton}); marching: {marched}"
    )


@pytest.mark.parametrize(
    ("hartmann", "cells", "ratio", "bound"),
    [
        (0.0, 16, None, 0.02),
        (5.0, 32, None, 0.02),
        (20.0, 32, 1.35, 0.02),
        (100.0, 48, 1.35, 0.01),
        (300.0, 48, 1.45, 0.02),
    ],
)
def test_the_steady_duct_matches_the_spectral_reference(hartmann, cells, ratio, bound):
    problem = _duct(cells, hartmann, ratio=ratio)
    solution = solve_steady_state(problem, pseudo_step=1.0e3)
    exact = REFERENCE_FLOW_RATE[hartmann]
    assert abs(_mean(problem, solution.velocity) - exact) / exact < bound


@pytest.mark.slow
def test_the_steady_duct_reaches_hartmann_1000():
    """The blanket-scale end of the range, where the Hartmann layer is a thousandth wide."""
    problem = _duct(64, 1000.0, ratio=1.5)
    solution = solve_steady_state(problem, pseudo_step=1.0e3, tolerance=1.0e-7, linear_restart=600)
    exact = REFERENCE_FLOW_RATE[1000.0]
    assert abs(_mean(problem, solution.velocity) - exact) / exact < 0.02


@pytest.mark.slow
def test_the_reference_values_are_what_the_spectral_solve_returns():
    """The constants above are cached results, so something has to regenerate them."""
    for hartmann, cached in REFERENCE_FLOW_RATE.items():
        spectral = quadrant_flow_rate(hartmann) if hartmann > 300.0 else flow_rate(hartmann, 64)
        assert spectral == pytest.approx(cached, rel=2e-4)


@pytest.mark.parametrize(
    ("cells", "hartmann", "conductance"), [(4, 0.0, 0.0), (10, 5.0, 0.0), (6, 5.0, 0.027)]
)
def test_the_adjoint_matches_finite_differences(cells, hartmann, conductance):
    """One linearised solve at the root, not a tape of the iteration."""
    problem = _duct(cells, hartmann, conductance=conductance)

    def throughput(drive, scale):
        solution = solve_steady_state(
            problem, pseudo_step=100.0, forcing=(drive, 0.0, 0.0), field_scale=scale
        )
        return jnp.mean(solution.velocity[0].data)

    value, gradient = jax.value_and_grad(throughput, argnums=(0, 1))(1.0, 1.0)
    compiled_value, compiled_gradient = jax.jit(jax.value_and_grad(throughput, argnums=(0, 1)))(1.0, 1.0)
    np.testing.assert_allclose(compiled_value, value, rtol=1e-10, atol=1e-12)
    np.testing.assert_allclose(compiled_gradient, gradient, rtol=1e-8, atol=1e-12)
    # The compiled objective is held to the eager one, then reused for the differences:
    # an eager call traces and compiles the steady solve every time, which was most of
    # this test's cost.
    compiled = jax.jit(throughput)
    assert float(compiled(1.0, 1.0)) == pytest.approx(float(value), rel=1e-10)
    size = 1.0e-5
    for index, argument in enumerate(((1.0, 1.0), (1.0, 1.0))):
        raised = list(argument)
        lowered = list(argument)
        raised[index] += size
        lowered[index] -= size
        difference = (compiled(*raised) - compiled(*lowered)) / (2.0 * size)
        assert float(gradient[index]) == pytest.approx(float(difference), rel=1e-6)
    # The Stokes limit is linear in the drive, so the derivative is the value itself.
    assert float(gradient[0]) == pytest.approx(float(value), rel=1e-12)


@pytest.mark.parametrize("conductance", [0.0, 0.027])
def test_the_reused_primal_is_the_general_adjoint(monkeypatch, conductance):
    """2b.2: a drive-weighted objective reuses the primal CG solve; the gradients are the general adjoint's."""
    import lmhdx.steady as steady

    problem = _duct(24, 100.0, conductance=conductance)
    areas = np.diff(problem.grid.y_faces)[:, None] * np.diff(problem.grid.z_faces)[None, :]

    def objectives(drive, scale):
        velocity = solve_steady_state(problem, forcing=(drive, 0.0, 0.0), field_scale=scale).velocity[0]
        flow = jnp.sum(areas * velocity.data[0])
        return flow, jnp.sum(velocity.data[0] ** 3)

    def gradients():
        flow = jax.jit(jax.value_and_grad(lambda d, s: objectives(d, s)[0], argnums=(0, 1)))(1.0, 1.0)
        cubic = jax.jit(jax.grad(lambda d, s: objectives(d, s)[1], argnums=(0, 1)))(1.0, 1.0)
        return np.array([flow[0], *flow[1], *cubic])

    reused = gradients()
    # Differentiating an enclosing jit re-enters the derivative rule outside the first trace.
    nested = jax.jit(jax.grad(jax.jit(lambda s: objectives(1.0, s)[0])))(1.0)
    np.testing.assert_allclose(nested, reused[2], rtol=1e-12, atol=0.0)
    monkeypatch.setattr(steady, "_REUSE_PRIMAL", False)
    general = gradients()
    np.testing.assert_allclose(reused, general, rtol=1e-9, atol=0.0)


@pytest.mark.parametrize(
    ("hartmann", "cells"),
    [(100.0, 24), pytest.param(300.0, 48, marks=pytest.mark.slow), (1000.0, 48)],
)
def test_the_adjoint_matches_finite_differences_where_the_layers_are_thin(hartmann, cells):
    """Stretched layer meshes need the preconditioned transpose; without it Ha 300 gave NaN.

    Ha 1000 is G11 and validation row 26 (plan step 1.7e): measured on 24, 48 and 64 cells
    at 2e-9 to 1.5e-7 of central differences with steps 1e-4 and 1e-5. Both the gradient
    and the differences are compiled; eager tracing of the solve was twice their cost.
    """
    problem = duct_problem(hartmann=hartmann, cells=cells)

    def throughput(drive, scale):
        solution = solve_steady_state(
            problem, pseudo_step=1.0e3, forcing=(drive, 0.0, 0.0), field_scale=scale
        )
        return jnp.mean(solution.velocity[0].data)

    value, gradient = jax.jit(jax.value_and_grad(throughput, argnums=(0, 1)))(1.0, 1.0)
    assert np.isfinite(value) and np.isfinite(gradient).all()
    compiled = jax.jit(throughput)
    size = 1.0e-4
    for index in range(2):
        raised = [1.0, 1.0]
        lowered = [1.0, 1.0]
        raised[index] += size
        lowered[index] -= size
        difference = (compiled(*raised) - compiled(*lowered)) / (2.0 * size)
        assert float(gradient[index]) == pytest.approx(float(difference), rel=1e-6)
    # A stronger field brakes the flow.
    assert float(gradient[1]) < 0.0


def _varying_duct(hartmann: float = 20.0, wall_conductance: float = 0.05) -> ChannelProblem:
    """``B_y`` varying along a duct with a thin wall, and a ``B_x`` across it of a tenth its strength."""
    duct = duct_problem(hartmann=hartmann, cells=24, wall_conductance=wall_conductance)
    grid = Grid(uniform_faces(4, 0.0, 4.0), duct.grid.y_faces, duct.grid.z_faces)
    x, y = grid.centers[0][:, None, None], grid.centers[1][None, :, None]
    along = hartmann * (0.75 + 0.25 * np.cos(np.pi * x / 2.0)) * np.ones(grid.shape)
    across = -0.1 * hartmann * np.sin(np.pi * x / 2.0) * y * np.ones(grid.shape)
    return dataclasses.replace(duct, grid=grid, magnetic_field=(across, along, 0.0))


@pytest.mark.parametrize(("hartmann", "conductance"), [(20.0, 0.0), (100.0, 0.05), (300.0, 0.0)])
def test_a_varying_field_certifies_at_the_default_tolerance(hartmann, conductance):
    """Issue #145: one projection left ~1e-13 of the removed gradient outside the divergence-free fields.

    The preconditioner cannot see that part of a residual, so CG stalled on it: 5e-10 of the right-hand
    side at Ha 20, 6.4e-7 at Ha 100, and no certificate at 1e-9 above Ha 20. Projecting the residual twice
    measured 122 / 794 / 2886 iterations here, with the certificate at 0.90 / 0.60 / 0.81 of its bound;
    the varying-field damping rate of 2b.4 takes them to 83 / 346 / 977.
    """
    from lmhdx.steady import _norm

    problem = _varying_duct(hartmann, conductance)
    solution = solve_steady_state(problem, pseudo_step=1.0e3)
    scale = float(_norm(steady_residual(zero_velocity(problem), problem)))
    assert float(solution.residual_norm) <= 10.0 * 1.0e-9 * scale and _mean(problem, solution.velocity) > 0.0


@pytest.mark.slow
@pytest.mark.parametrize(("hartmann", "tolerance"), [(300.0, 1.0e-9), (600.0, 1.0e-8), (1000.0, 1.0e-7)])
def test_the_fringe_certifies_at_the_tolerance_rule(hartmann, tolerance):
    """The rule for steps 1.9b-1.9d: 1e-9 through Ha 300, 1e-8 to Ha 600, 1e-7 to Ha 1000, 36000 CG steps above 300.

    The ANL fringe on 24 cells with 16 axial ones: CG's floor with the residual projected twice is 1.5e-10 at
    Ha 300, 7.5e-10 at Ha 600 and 1.5e-8 at Ha 1000, where round-off in the potential solve leaves the operator
    asymmetric by 6e-7. Each tolerance is at least 6.7 times its floor; the solves took 5581 / 12,056 / 19,299
    iterations, so the budget above Ha 300 keeps 1.9 times headroom. With the varying-field damping rate
    of 2b.4 they take 1361 / 2508 / 3822 iterations.
    """
    from lmhdx.core3d import fringe_field

    duct = duct_problem(hartmann=hartmann, cells=24)
    grid = Grid(uniform_faces(16, -8.0, 8.0), duct.grid.y_faces, duct.grid.z_faces)
    field = fringe_field(grid, strength=hartmann, solenoidal=False)
    problem = dataclasses.replace(duct, grid=grid, magnetic_field=field)
    restarts = 200 if hartmann <= 300.0 else 600
    solution = solve_steady_state(
        problem, pseudo_step=1.0e3, tolerance=tolerance, linear_max_restarts=restarts
    )
    assert np.isfinite(float(solution.residual_norm)) and _mean(problem, solution.velocity) > 0.0


def test_a_varying_field_takes_the_damped_preconditioner_and_still_converges():
    """The field-line solve is exact only for a uniform axis-aligned field, so a varying one falls back.

    Every component then takes one damped inverse, at the rate of :func:`lmhdx.steady._varying_field_rate`:
    well below the peak ``|B|^2`` (2b.4), and the same for all three, since a damping that differs by
    component reopens the Schur-complement deficit. The operator stays symmetric to the round-off of this
    layer mesh (8e-12 for a uniform field) and CG certifies the solve at the default tolerance, which took
    1e-8 before #145.
    """
    from lmhdx.poisson import FastDiagonalHelmholtz
    from lmhdx.steady import _projection_solves, _varying_field_rate

    problem = _varying_duct()
    solves = _projection_solves(problem, 1.0e3)
    peak = float(
        np.max(problem.magnetic_field.components[0] ** 2 + problem.magnetic_field.components[1] ** 2)
    )
    rate = _varying_field_rate(problem)
    # Walls at y, z = +-1 and a periodic axis: the slowest viscous rate is about 2 (pi/2)^2.
    slowest = 2.0 * (np.pi / 2.0) ** 2
    assert rate == pytest.approx(slowest**0.75 * peak**0.25, rel=0.05) and rate < 0.1 * peak
    assert all(
        isinstance(solve, FastDiagonalHelmholtz) and solve.shift == pytest.approx(1.0 + 1.0e3 * rate)
        for solve in solves
    )
    forward, backward, energy = _stokes_operator_samples(problem)
    assert abs(forward - backward) <= 1e-11 * max(abs(forward), abs(backward)) and energy < 0.0
    solution = solve_steady_state(problem, pseudo_step=1.0e3)
    assert np.isfinite(float(solution.residual_norm)) and _mean(problem, solution.velocity) > 0.0


@pytest.mark.parametrize("hartmann", [20.0, 100.0])
def test_the_adjoint_matches_finite_differences_in_a_varying_field(hartmann):
    """Plan step 1.9a: ``B_y`` varying along the duct and a ``B_x`` across it, with a thin wall.

    Measured against central differences at Ha 20: 3.1e-11 in the drive and 5.8e-9 in the field scale
    (4.3e-9 without the wall). Ha 100 held only once the residual was projected twice (#145).
    """
    problem = _varying_duct(hartmann)

    def throughput(drive, scale):
        solution = solve_steady_state(
            problem, pseudo_step=1.0e3, forcing=(drive, 0.0, 0.0), field_scale=scale, tolerance=1.0e-9
        )
        return jnp.mean(solution.velocity[0].data)

    _, gradient = jax.jit(jax.value_and_grad(throughput, argnums=(0, 1)))(1.0, 1.0)
    compiled, size = jax.jit(throughput), 1.0e-4
    for index in range(2):
        raised, lowered = [1.0, 1.0], [1.0, 1.0]
        raised[index] += size
        lowered[index] -= size
        difference = (compiled(*raised) - compiled(*lowered)) / (2.0 * size)
        assert float(gradient[index]) == pytest.approx(float(difference), rel=1e-6)
    assert float(gradient[1]) < 0.0


def _random_velocity(problem: ChannelProblem, seed: int):
    """A random velocity with no constraint imposed: wall faces and periodic copies are free."""
    from lmhdx.core3d import velocity_offset
    from lmhdx.grid import Field

    keys = jax.random.split(jax.random.PRNGKey(seed), 3)
    return tuple(
        Field(
            jax.random.normal(
                keys[axis], problem.grid.offset_shape(velocity_offset(axis)), dtype=jnp.float64
            ),
            velocity_offset(axis),
            problem.grid,
        )
        for axis in range(3)
    )


def _face_volume_inner(problem: ChannelProblem, left, right) -> float:
    from lmhdx.core3d import velocity_condition
    from lmhdx.ops import face_inner_product

    return sum(
        float(face_inner_product(a, b, axis, velocity_condition(problem.conditions, axis)))
        for axis, (a, b) in enumerate(zip(left, right, strict=True))
    )


def _stokes_operator_samples(problem: ChannelProblem):
    """Return <v, A u>, <u, A v> and <u, A u> for two random divergence-free velocities."""
    from lmhdx.core3d import project

    factorization = problem.factorization()
    rest = steady_residual(zero_velocity(problem), problem, factorization)

    def operator(velocity):
        value = steady_residual(velocity, problem, factorization)
        return tuple(
            field.replace_data(field.data - base.data) for field, base in zip(value, rest, strict=True)
        )

    u, v = (project(_random_velocity(problem, seed), problem, factorization)[0] for seed in (1, 2))
    inner = functools.partial(_face_volume_inner, problem)
    return inner(v, operator(u)), inner(u, operator(v)), inner(u, operator(u))


def _extruded(problem: ChannelProblem, axial_cells: int, hartmann: float, cells: int) -> ChannelProblem:
    """The same duct cross-section repeated over several periodic axial cells."""
    transverse = wall_resolving_faces(
        cells, -1.0, 1.0, layer_thickness=1.0 / hartmann, cells_in_layer=6, max_ratio=None
    )
    spanwise = wall_resolving_faces(
        cells, -1.0, 1.0, layer_thickness=1.0 / np.sqrt(hartmann), cells_in_layer=6, max_ratio=None
    )
    return dataclasses.replace(problem, grid=Grid(uniform_faces(axial_cells, 0.0, 1.0), transverse, spanwise))


def test_the_conjugate_gradient_preconditioner_is_symmetric_positive_definite():
    """CG needs the preconditioner symmetric positive definite in the same inner product as the operator.

    Several axial cells, because the periodic wrap face is where a one-cell
    duct hides an error: the viscous solve returns the duplicate face as zero,
    and completing it by averaging instead of copying made the axial viscous
    inverse asymmetric by 2.7e-2 on a 24-cube Ha 20 duct, and CG took 320
    iterations instead of 119.
    """
    from lmhdx.core3d import project
    from lmhdx.steady import _orthogonal_projection, _preconditioner, _projection_solves

    problem = _extruded(duct_problem(hartmann=100.0, cells=24), 4, 100.0, 24)
    factorization = problem.factorization()
    precond = _preconditioner(problem, factorization, _projection_solves(problem, 1.0e3), 1.0e3)
    inner = functools.partial(_face_volume_inner, problem)

    u, v = _random_velocity(problem, 1), _random_velocity(problem, 2)
    orthogonal = functools.partial(_orthogonal_projection, problem=problem, factorization=factorization)
    assert abs(inner(v, orthogonal(u)) - inner(orthogonal(v), u)) <= 1e-12 * abs(inner(v, orthogonal(u)))
    # The oblique projection the time step uses is not self-adjoint, which is why the adjoint needs the other.
    oblique = project(u, problem, factorization)[0], project(v, problem, factorization)[0]
    assert abs(inner(v, oblique[0]) - inner(oblique[1], u)) > 1e-3 * abs(inner(v, oblique[0]))

    up, vp = orthogonal(_random_velocity(problem, 3)), orthogonal(_random_velocity(problem, 4))
    forward, backward = inner(vp, precond(up)), inner(up, precond(vp))
    # The eigenbases of a stretched axis carry about 1e-9; the wrap-face defect was 2.7e-2.
    assert abs(forward - backward) <= 1e-8 * max(abs(forward), abs(backward))
    assert inner(up, precond(up)) > 0.0 and inner(vp, precond(vp)) > 0.0


def _conjugate_gradient_iterations(problem: ChannelProblem, solves) -> int:
    """CG iterations of the insulating steady solve from rest, with the given projection-step solves."""
    from lmhdx.steady import _orthogonal_projection, _preconditioner, _stokes_limit_root

    factorization = problem.factorization()
    precond = _preconditioner(problem, factorization, solves(problem, 1.0e3), 1.0e3)
    start = _orthogonal_projection(zero_velocity(problem), problem, factorization)
    controls = dict(forcing=None, field_scale=1.0, tolerance=1.0e-9, max_iterations=12000)
    _, (iterations, _, converged) = _stokes_limit_root(problem, start, factorization, precond, **controls)
    assert bool(converged)
    return int(iterations)


@pytest.mark.parametrize(
    ("hartmann", "cells", "bound"),
    [(300.0, 48, 70), pytest.param(1000.0, 64, 110, marks=pytest.mark.slow)],
)
def test_field_lines_cut_the_iterations_where_the_layers_are_thin(hartmann, cells, bound):
    """Field lines take CG from 403 to 44 iterations at Ha 300 and from 714 to 68 at Ha 1000.

    Round-off in the secondary components seeds part of the count, hence ~60 % headroom; the
    1.10b parity gate is 300 at Ha 1000.
    """
    from lmhdx.steady import _isotropic_viscous, _projection_solves

    problem = duct_problem(hartmann=hartmann, cells=cells)
    lines = _conjugate_gradient_iterations(problem, _projection_solves)
    assert lines <= bound, f"field lines took {lines} iterations"
    damped = _conjugate_gradient_iterations(problem, _isotropic_viscous)
    assert 6 * lines <= damped, f"field lines {lines}, damped {damped}"


def test_field_lines_invert_the_fully_developed_operator_on_a_uniform_mesh():
    """On a uniform mesh the induction form is the discrete operator: 3 iterations at Ha 300, 218 damped."""
    from lmhdx.steady import _projection_solves

    assert _conjugate_gradient_iterations(_duct(24, 300.0), _projection_solves) <= 5


def test_field_line_inverses_match_the_banded_solve(monkeypatch):
    """The GPU applies each line's velocity-block inverse; the banded substitutions agree, as do the pullbacks."""
    from lmhdx import steady

    problem = _extruded(duct_problem(hartmann=10.0, cells=16), 3, 10.0, 16)
    monkeypatch.setattr(steady, "_LINE_INVERSE_BACKENDS", (jax.default_backend(),))
    dense = steady._FieldLine(problem, 0, 1, 1.0e3)
    monkeypatch.setattr(steady, "_LINE_INVERSE_BYTES", -1)
    banded = steady._FieldLine(problem, 0, 1, 1.0e3)
    assert dense.dense and not banded.dense
    rhs = zero_velocity(problem)[0]
    rhs = rhs.replace_data(jnp.asarray(np.random.default_rng(0).standard_normal(rhs.data.shape)))
    for route in (lambda solve: solve(rhs), lambda solve: jax.vjp(solve, rhs)[1](rhs)[0]):
        expected = route(banded.solve).data
        error = float(jnp.max(jnp.abs(route(dense.solve).data - expected)))
        assert error <= 1e-13 * float(jnp.max(jnp.abs(expected)))


def test_the_conjugate_gradient_route_agrees_with_newton_krylov():
    """A unidirectional duct flow does not advect itself, so both routes answer the same question.

    Without advection the steady state is one CG solve; with the central
    advection switched on it goes through Newton-GMRES, whose restart cycle is
    what memory allows in three dimensions. The advective flux needs more than
    one axial cell, so both ducts are extruded.
    """
    symmetric = _extruded(duct_problem(hartmann=100.0, cells=24), 4, 100.0, 24)
    advective = _extruded(duct_problem(hartmann=100.0, cells=24, advection="central"), 4, 100.0, 24)
    cg = solve_steady_state(symmetric, pseudo_step=1.0e3).velocity
    newton = solve_steady_state(advective, pseudo_step=1.0e3).velocity
    size = max(float(jnp.max(jnp.abs(field.data))) for field in newton)
    difference = max(float(jnp.max(jnp.abs(a.data - b.data))) for a, b in zip(cg, newton, strict=True))
    assert difference <= 1e-8 * size


def test_a_periodic_extrusion_reproduces_the_duct_by_conjugate_gradients():
    """Six axial cells carry the one-cell solution; round-off excites the axial modes CG must still resolve."""
    duct = duct_problem(hartmann=20.0, cells=24)
    flat = solve_steady_state(duct, pseudo_step=1.0e3).velocity[0].data
    deep = solve_steady_state(_extruded(duct, 6, 20.0, 24), pseudo_step=1.0e3).velocity[0].data
    assert float(jnp.max(jnp.abs(deep - flat[:1]))) <= 1e-8 * float(jnp.max(jnp.abs(flat)))


def test_mixed_precision_reaches_the_same_steady_duct():
    """Float32 fast solves with a float64 correction keep CG's operator linear enough."""
    duct = duct_problem(hartmann=20.0, cells=24)
    state = _mean(duct, solve_steady_state(duct, pseudo_step=1.0e3).velocity)
    mixed_duct = dataclasses.replace(duct, precision="mixed")
    mixed = _mean(mixed_duct, solve_steady_state(mixed_duct, pseudo_step=1.0e3).velocity)
    assert mixed == pytest.approx(state, rel=1e-9)


@pytest.mark.parametrize("conductance", [0.0, 0.05, (0.0, 0.0, 0.05)])
def test_the_stokes_operator_is_symmetric_on_a_layer_mesh(conductance):
    """The electromotive and force interpolations are adjoint, so conjugate gradients apply.

    The Stokes-limit residual is affine in the velocity. Its linear part was
    symmetric in the face-volume inner product on a uniform mesh and 1e-2 away
    from it on this one, because the force was interpolated with a stencil that
    was not the transpose of the electromotive one. A thin conducting wall is a
    sheet of potential joined to the fluid by the half-cell flux and solved
    directly, so it keeps the operator symmetric as well.
    """
    # The last case conducts along the side walls, parallel to the field: 1.1e-3 asymmetric at Ha 20 while
    # the half-cell current into a wall pushed on the field with no electromotive force to match.
    walls = conductance if isinstance(conductance, tuple) else (0.0, conductance, 0.0)
    problem = dataclasses.replace(duct_problem(hartmann=100.0, cells=32), wall_conductance=walls)
    forward, backward, energy = _stokes_operator_samples(problem)
    asymmetry = abs(forward - backward) / max(abs(forward), abs(backward))
    assert asymmetry <= 1e-12
    # Viscosity and Joule dissipation both remove energy.
    assert energy < 0.0


@pytest.mark.parametrize("conductance", [0.0, 0.05])
def test_the_stokes_operator_stays_symmetric_in_a_varying_field(conductance):
    """Plan step 1.9a: the ANL fringe and its solenoidal pair on a layer mesh, so conjugate gradients still apply.

    Without the wall-face closure of :func:`lmhdx.core3d.electric_state` a thin wall's half-cell current
    pushed on the fringe's ``B_x`` with no electromotive force to match: 1.0e-6 asymmetric at Ha 20.
    """
    from lmhdx.core3d import fringe_field

    duct = duct_problem(hartmann=100.0, cells=32, wall_conductance=conductance)
    grid = Grid(uniform_faces(8, -6.0, 6.0), duct.grid.y_faces, duct.grid.z_faces)
    problem = dataclasses.replace(duct, grid=grid, magnetic_field=fringe_field(grid, strength=100.0))
    forward, backward, energy = _stokes_operator_samples(problem)
    assert abs(forward - backward) <= 1e-12 * max(abs(forward), abs(backward))
    assert energy < 0.0


def test_a_solve_that_does_not_converge_raises():
    """A plausible field and a gradient taken away from a root are worse than an error."""
    problem = _duct(16, 20.0)
    with pytest.raises(RuntimeError, match="did not converge"):
        solve_steady_state(problem, pseudo_step=1.0e3, max_steps=1, linear_restart=1, linear_max_restarts=1)


@pytest.mark.parametrize("drive", [1.0, np.nan, np.inf])
def test_a_rejected_root_cannot_produce_a_finite_objective_or_gradient(drive):
    problem = _duct(4, 0.0)

    def objective(drive):
        solution = solve_steady_state(problem, forcing=(drive, 0.0, 0.0), max_steps=0)
        return jnp.mean(solution.velocity[0].data)

    with pytest.raises(RuntimeError, match="did not converge"):
        objective(drive)
    value, gradient = jax.value_and_grad(objective)(drive)
    assert not np.isfinite(value) and not np.isfinite(gradient)
    value, gradient = jax.jit(jax.value_and_grad(objective))(drive)
    assert not np.isfinite(value) and not np.isfinite(gradient)


def test_a_failed_tangent_solve_is_rejected_eagerly_and_under_jit():
    from lmhdx.steady import _krylov, _tangent_solve

    def solve(rhs):
        return _krylov(jnp.zeros_like, rhs)

    with pytest.raises(RuntimeError, match="linear solve did not converge"):
        solve(jnp.ones(2))
    assert not np.isfinite(jax.jit(solve)(jnp.ones(2))).all()
    value, gradient = jax.value_and_grad(lambda rhs: jnp.sum(_tangent_solve(jnp.zeros_like, rhs)))(
        jnp.ones(2)
    )
    assert not np.isfinite(value) and not np.isfinite(gradient).all()


@pytest.mark.parametrize("name", ["pseudo_step", "tolerance", "linear_tolerance"])
@pytest.mark.parametrize("value", [0.0, -1.0, np.nan, np.inf])
def test_the_solver_controls_are_validated(name, value):
    with pytest.raises(ValueError, match=f"{name} must be positive and finite"):
        solve_steady_state(_duct(4, 0.0), **{name: value})


@pytest.mark.parametrize("conductance", [0.027, 0.100])
def test_a_hunt_duct_matches_the_spectral_reference(conductance):
    """Conducting Hartmann walls carry the current the layer would otherwise have to."""
    problem = _duct(32, 20.0, ratio=1.35, conductance=conductance)
    solution = solve_steady_state(problem, pseudo_step=1.0e3)
    rate = _mean(problem, solution.velocity)
    exact = HUNT_FLOW_RATE[20.0, conductance]
    assert abs(rate - exact) / exact < 0.02
    # A conducting wall short-circuits the Hartmann layer, so it always slows the flow.
    assert rate < REFERENCE_FLOW_RATE[20.0]
    # Plan step 1.3: the wall current within 1 % of the series solution. The normal current
    # on each Hartmann wall's faces, half-integrated as the reference is; measured 0.64 %
    # (c 0.027) and 0.45 % (c 0.1) high, 0.50 % at 48 cells.
    normal = np.abs(np.asarray(solution.currents[1].data)[0])
    widths = np.diff(problem.grid.z_faces)
    current = HUNT_WALL_CURRENT[conductance]
    for wall in (normal[0], normal[-1]):
        assert abs(0.5 * float(wall @ widths) - current) / current < 0.01


def test_a_wall_of_no_conductance_is_the_insulating_duct():
    """The conducting closure has to collapse onto the one it generalises."""
    rates = [
        _mean(problem, solve_steady_state(problem, pseudo_step=100.0).velocity)
        for problem in (_duct(16, 5.0), _duct(16, 5.0, conductance=0.0))
    ]
    assert rates[0] == rates[1]


@pytest.mark.parametrize("conductance", [0.0, 0.027])
def test_the_answer_follows_the_hartmann_number_and_not_the_conductivity(conductance):
    """Only `sigma B^2` is physical, so the potential has to be scaled by sigma, and a sheet's conduction with it."""
    rates = [
        _mean(problem, solve_steady_state(problem, pseudo_step=100.0).velocity)
        for problem in (
            _duct(16, 5.0, conductance=conductance),
            _duct(16, 5.0, conductance=conductance, conductivity=4.0),
        )
    ]
    assert rates[0] == pytest.approx(rates[1], rel=1e-12)


@pytest.mark.slow
def test_the_hunt_reference_values_are_what_the_spectral_solve_returns():
    for (hartmann, conductance), cached in HUNT_FLOW_RATE.items():
        spectral = (
            quadrant_flow_rate(hartmann, hartmann_wall=conductance)
            if hartmann > 100.0
            else flow_rate(hartmann, 64, hartmann_wall=conductance)
        )
        assert spectral == pytest.approx(cached, rel=2e-4)
    for conductance, cached in HUNT_WALL_CURRENT.items():
        assert hartmann_wall_current(20.0, hartmann_wall=conductance) == pytest.approx(cached, rel=1e-7)


@pytest.mark.parametrize(
    ("variation", "bound"), [(0.2, 1e-2), pytest.param(0.1, 5e-3, marks=pytest.mark.slow)]
)
def test_each_station_of_a_gradually_varying_field_carries_its_local_shercliff_profile(variation, bound):
    """Plan step 1.9a: ``B_y = 20 (1 + e cos(2 pi x / 32))``, variation length 25 (e = 0.2) and 50 (e = 0.1).

    Bounds fixed before running: each station's profile, normalised by the flow rate, within 3 % of the
    spectral one at its own field (the uniform-field mesh error here is 2 %) and within 1 % of this mesh's
    uniform-field solve, half that at twice the length. Measured: 0.72 % and 0.25 % at 25, 0.66 % and
    0.076 % at 50. The local pressure gradient is not local to the same degree: 4.6 % and 2.3 % from the
    uniform-field value, halving with the curvature of the field.
    """
    from scipy.interpolate import BarycentricInterpolator

    from validation.shercliff import duct_flow

    duct = duct_problem(hartmann=20.0 * (1.0 + variation), cells=24)
    grid = Grid(uniform_faces(16, 0.0, 32.0), duct.grid.y_faces, duct.grid.z_faces)
    field = 20.0 * (1.0 + variation * np.cos(np.pi * grid.centers[0] / 16.0))
    problem = dataclasses.replace(
        duct, grid=grid, magnetic_field=(0.0, field[:, None, None] * np.ones(grid.shape), 0.0)
    )
    axial = np.asarray(solve_steady_state(problem, pseudo_step=1.0e3, tolerance=1.0e-8).velocity[0].data)
    volumes = np.asarray(grid.cell_volumes())[0]
    for face in (0, 4, 8):
        hartmann = 0.5 * (field[face - 1] + field[face])
        local = dataclasses.replace(duct, magnetic_field=(0.0, hartmann, 0.0))
        uniform = np.asarray(solve_steady_state(local, pseudo_step=1.0e3).velocity[0].data)[0]
        nodes, spectral, _ = duct_flow(hartmann, 40)
        spectral = BarycentricInterpolator(nodes, spectral, axis=0)(grid.centers[1])
        spectral = BarycentricInterpolator(nodes, spectral, axis=1)(grid.centers[2])
        station = axial[face] / np.sum(axial[face] * volumes)
        for reference, tolerance in ((spectral, 3e-2), (uniform, bound)):
            shape = reference / np.sum(reference * volumes)
            assert np.max(np.abs(station - shape)) <= tolerance * np.max(shape)


def test_the_steady_state_closes_its_mechanical_power_balance():
    """What the drive and the field put in is what viscosity takes out, to round-off.

    The pressure does no work on a discretely divergence-free velocity, so this
    is the residual of the steady solve projected onto the velocity itself: an
    independent reading of the same claim, in energy rather than in momentum.
    """
    from lmhdx.timeloop import energy_budget

    for conductance in (0.0, 0.027):
        problem = _duct(32, 20.0, ratio=1.35, conductance=conductance)
        budget = energy_budget(solve_steady_state(problem, pseudo_step=1.0e3).velocity, problem)
        assert abs(float(budget.defect / budget.scale)) < 1e-10
        assert float(budget.drive) > 0.0
        assert float(budget.viscous) > 0.0


def test_a_new_field_on_the_same_mesh_reuses_the_compiled_solve(monkeypatch):
    """2b.1: the arrays a solve closes over are arguments, so one executable serves every field."""
    import lmhdx._programs as _programs
    import lmhdx.steady as steady

    # In-process sharing only: what earlier processes stored in the cache directory is not read.
    monkeypatch.setattr(_programs, "_store_path", lambda key, suffix: None)
    monkeypatch.setattr(steady, "_SHAPES", {})
    base = _duct(24, 20.0, conductance=0.027)
    for hartmann in (20.0, 30.0, 40.0):
        problem = dataclasses.replace(base, magnetic_field=(0.0, hartmann, 0.0))
        shared = steady.solve_compiled(problem).velocity
        embedded = jax.jit(steady._solve_program(problem))()[0]
        for got, expected in zip(shared, embedded, strict=True):
            np.testing.assert_allclose(got.data, expected.data, rtol=1e-12, atol=1e-14)
    # The first problem of the shape embeds its constants; the second compiles the shared program,
    # which the third reuses.
    (entry,) = steady._SHAPES.values()
    assert isinstance(entry, _programs.ShapeProgram)
    monkeypatch.setattr(steady, "_EMBED_AFTER_CALLS", 1)
    steady._program.cache_clear()
    repeated = dataclasses.replace(base, magnetic_field=(0.0, 50.0, 0.0))
    first = steady.solve_compiled(repeated).velocity
    again = steady.solve_compiled(repeated).velocity  # past the threshold: its own embedded program
    for got, expected in zip(again, first, strict=True):
        np.testing.assert_allclose(got.data, expected.data, rtol=1e-12, atol=1e-14)


@pytest.mark.parametrize("conductance", [0.0, 0.027])
def test_a_new_mesh_of_a_known_shape_is_solved_without_a_trace(monkeypatch, conductance):
    """2b.1 stage 5: from the third problem of a shape on, the solve is never traced.

    Each Hartmann number clusters its own mesh, so the grid metric, the field and every
    factorization differ; they are built on the host and passed to the shape's program.
    """
    import lmhdx._programs as _programs
    import lmhdx.steady as steady

    # In-process sharing only: what earlier processes stored in the cache directory is not read.
    monkeypatch.setattr(_programs, "_store_path", lambda key, suffix: None)
    monkeypatch.setattr(steady, "_SHAPES", {})
    steady._program.cache_clear()
    traces = []
    original = steady.solve_steady_state

    def counted(*arguments, **keywords):
        traces.append(1)
        return original(*arguments, **keywords)

    monkeypatch.setattr(steady, "solve_steady_state", counted)
    counts = []
    for hartmann in (20.0, 30.0, 45.0):
        problem = duct_problem(hartmann=hartmann, cells=16, cells_in_layer=2, wall_conductance=conductance)
        before = len(traces)
        shared = steady.solve_compiled(problem).velocity
        counts.append(len(traces) - before)
        embedded = jax.jit(steady._solve_program(problem))()[0]
        for got, expected in zip(shared, embedded, strict=True):
            np.testing.assert_allclose(got.data, expected.data, rtol=1e-12, atol=1e-14)
            assert got.grid is problem.grid
    assert counts == [1, 1, 0]


_PROCESS = """
import json, sys
import jax, jax.numpy as jnp
import lmhdx
lmhdx.enable_x64()
jax.config.update("jax_persistent_cache_min_compile_time_secs", 0.0)
from lmhdx import _programs, steady
from lmhdx.core3d import duct_problem
traces = []
original = steady.solve_steady_state
steady.solve_steady_state = lambda *a, **k: traces.append(1) or original(*a, **k)
flows = [float(jnp.sum(steady.solve_compiled(duct_problem(hartmann=h, cells=16, cells_in_layer=2)).velocity[0].data))
         for h in map(float, sys.argv[1:])]
kinds = [type(entry).__name__ for entry in steady._SHAPES.values()]
broken = sum(getattr(entry, "broken", False) for entry in _programs._GRID_PROGRAMS.values())
print(json.dumps({"flows": flows, "traces": len(traces), "kinds": kinds, "broken": broken}))
"""


def test_a_known_shape_is_solved_in_a_new_process_without_a_trace(tmp_path):
    """2b.1: a shape's keys and compiled program are kept beside the compilation cache.

    Three processes share one cache, as CI shards and users do. The second rebuilds the
    stored program while JAX's cache holds its executable: one read back from that cache
    serializes without its fused kernels, so the store must compile its own. The third
    then runs the stored program with no trace and matches the first to round-off.
    """
    import json
    import shutil
    import subprocess
    import sys

    environment = {**os.environ, "JAX_PLATFORMS": "cpu"}
    # Either variable may name the cache; a runner that sets JAX's own would otherwise win.
    environment.update(
        LMHDX_COMPILATION_CACHE=str(tmp_path),
        JAX_COMPILATION_CACHE_DIR=str(tmp_path),
        JAX_ENABLE_COMPILATION_CACHE="true",
    )

    def process(*hartmanns):
        completed = subprocess.run(
            [sys.executable, "-c", _PROCESS, *map(str, hartmanns)],
            env=environment,
            capture_output=True,
            text=True,
            check=True,
        )
        return json.loads(completed.stdout.strip().splitlines()[-1])

    first = process(20.0, 30.0)
    shutil.rmtree(tmp_path / "lmhdx_shapes")
    process(20.0, 30.0)
    third = process(30.0)
    assert third["traces"] == 0
    assert third["broken"] == 0
    assert third["kinds"] == ["_StoredProgram"]
    assert third["flows"][0] == pytest.approx(first["flows"][1], rel=1e-12)


def test_a_program_stored_on_another_cpu_is_never_loaded(monkeypatch, tmp_path):
    """2b.1: a stored executable runs only on the CPU that compiled it.

    One loaded on a CPU without its instructions dies of an illegal instruction, which no
    fallback can catch. The fingerprint is in the key and in the entry: an entry whose
    fingerprint differs is ignored and the solve traced, to round-off of its embedded program.
    """
    import pickle

    import lmhdx._programs as _programs
    import lmhdx.steady as steady

    previous = jax.config.jax_compilation_cache_dir
    jax.config.update("jax_compilation_cache_dir", str(tmp_path))
    try:
        problems = [duct_problem(hartmann=h, cells=16, cells_in_layer=2) for h in (20.0, 30.0, 45.0)]
        monkeypatch.setattr(steady, "_SHAPES", {})
        monkeypatch.setattr(_programs, "_GRID_PROGRAMS", {})
        steady._program.cache_clear()
        for problem in problems[:2]:
            steady.solve_compiled(problem)
        programs = sorted((tmp_path / "lmhdx_shapes").glob("*.program"))
        assert programs
        for path in programs:
            _, *payload = pickle.loads(path.read_bytes())
            path.write_bytes(pickle.dumps(("another cpu", *payload)))
        monkeypatch.setattr(steady, "_SHAPES", {})
        monkeypatch.setattr(_programs, "_GRID_PROGRAMS", {})
        steady._program.cache_clear()
        solution = steady.solve_compiled(problems[2]).velocity
        assert not any(isinstance(entry, _programs._StoredProgram) for entry in steady._SHAPES.values())
        assert not any(
            isinstance(entry, _programs._StoredProgram) for entry in _programs._GRID_PROGRAMS.values()
        )
        embedded = jax.jit(steady._solve_program(problems[2]))()[0]
        for got, expected in zip(solution, embedded, strict=True):
            np.testing.assert_allclose(got.data, expected.data, rtol=1e-12, atol=1e-14)
    finally:
        jax.config.update("jax_compilation_cache_dir", previous)
        steady._program.cache_clear()


def _extruded_duct(hartmann: float) -> ChannelProblem:
    duct = duct_problem(hartmann=hartmann, cells=10, cells_in_layer=1)
    return dataclasses.replace(
        duct, grid=Grid(uniform_faces(4, 0.0, 4.0), duct.grid.y_faces, duct.grid.z_faces)
    )


def _varying(hartmann: float) -> ChannelProblem:
    duct = duct_problem(hartmann=hartmann, cells=10, cells_in_layer=1)
    grid = Grid(uniform_faces(4, 0.0, 8.0), duct.grid.y_faces, duct.grid.z_faces)
    field = hartmann * (1.0 + 0.2 * np.cos(np.pi * grid.centers[0] / 4.0))
    return dataclasses.replace(
        duct, grid=grid, magnetic_field=(0.0, field[:, None, None] * np.ones(grid.shape), 0.0)
    )


_FAMILIES = {
    "duct": lambda hartmann: duct_problem(hartmann=hartmann, cells=12, cells_in_layer=2),
    "hunt": lambda hartmann: duct_problem(
        hartmann=hartmann, cells=12, cells_in_layer=2, wall_conductance=0.027
    ),
    "three-dimensional": _extruded_duct,
    "varying field": _varying,
    "mixed precision": lambda hartmann: dataclasses.replace(
        duct_problem(hartmann=hartmann, cells=12, cells_in_layer=2), precision="mixed"
    ),
}


@pytest.mark.parametrize("route", ["steady", "fully developed"])
@pytest.mark.parametrize("family", sorted(_FAMILIES))
def test_the_shared_program_holds_no_value_of_the_problem(family, route):
    """2b.1 stage 5: two problems of a shape lower to the same program, which solves each to round-off.

    A number or an array of one problem left in the trace would change the lowered text
    and give every later problem that problem's value; the fingerprint is that text.
    ``route`` is the program of :func:`lmhdx.steady.solve_compiled` or the unit-drive
    program of :func:`lmhdx.solve`, whose argument is the field scale.
    """
    import lmhdx._programs as _programs
    import lmhdx.fully_developed as fully_developed
    import lmhdx.steady as steady

    if route == "steady":
        build, arguments, values = steady._solve_program, (), ()
    else:
        dtype = jnp.result_type(float)
        build, arguments = fully_developed._unit_drive, (jax.ShapeDtypeStruct((), dtype),)
        values = (np.asarray(1.3, dtype=dtype),)
    first, *problems = (_FAMILIES[family](hartmann) for hartmann in (20.0, 30.0, 45.0))
    with _programs.discovering(first) as trace:
        jax.jit(build(first)).lower(*arguments)
    assert trace.complete
    keys = list(trace.keys)
    programs = [_programs.ShapeProgram(build, problem, arguments, keys) for problem in problems]
    assert programs[0].fingerprint == programs[1].fingerprint
    for problem in problems:
        shared = jax.tree.leaves(programs[0].bind(problem)(*values))
        embedded = jax.tree.leaves(jax.jit(build(problem))(*values))
        # Fields against the largest one (the transverse velocities are round-off); the varying
        # field stops CG at 1e-9, which amplifies round-off to about 1e-11. Of the numbers, the
        # residual norms are where CG stopped, round-off themselves, and the flow rate is compared.
        scale = max(float(np.max(np.abs(leaf))) for leaf in embedded)
        for got, expected in zip(shared, embedded, strict=True):
            if np.ndim(expected):
                np.testing.assert_allclose(got, expected, rtol=0.0, atol=1e-10 * scale)
            elif abs(float(expected)) > 1e-6 * scale:
                np.testing.assert_allclose(got, expected, rtol=1e-10)


@pytest.mark.parametrize("conductance", [0.0, 0.027])
def test_the_residual_at_rest_is_the_projected_drive_exactly(conductance):
    """The solve's starting residual skips the operator; it must be the full residual bit for bit."""
    from lmhdx.steady import _rest_residual

    problem = _duct(24, 20.0, conductance=conductance)
    factorization = problem.factorization()
    full = steady_residual(
        zero_velocity(problem), problem, factorization, forcing=(2.5, 0.0, 0.0), field_scale=1.3
    )
    for got, expected in zip(_rest_residual(problem, factorization, (2.5, 0.0, 0.0)), full, strict=True):
        np.testing.assert_array_equal(got.data, expected.data)


def test_a_solve_from_rest_traces_the_operator_twice(monkeypatch):
    """Once in the CG iteration and once to certify the root: not at rest, nor on CG's zero start."""
    import lmhdx.steady as steady

    calls = []
    original = steady.steady_residual

    def counted(*arguments, **keywords):
        calls.append(1)
        return original(*arguments, **keywords)

    monkeypatch.setattr(steady, "steady_residual", counted)
    problem = _duct(24, 20.0)
    jax.make_jaxpr(lambda: solve_steady_state(problem).velocity)()
    assert len(calls) == 2
